import openai
import os
import cv2
import base64
from src.config.config import endpoint, api_key as AZURE_API_KEY
from azure.ai.inference import ChatCompletionsClient
from azure.ai.inference.models import SystemMessage, UserMessage
from azure.core.credentials import AzureKeyCredential
import time
def get_spatial_context_description(frame, found_detections, target_detection, label, api_key=None, endpoint_url=None, model_name="gpt-4o"):
    """
    Uses Azure OpenAI GPT-4o to generate a spatial context description for the given frame and detections, focusing on the given label.
    Args:
        frame (numpy.ndarray): The image frame (will be encoded to base64 for vision input).
        found_detections (list): List of detection dicts/tuples with bounding boxes and class labels.
        label (str): The object label to focus the spatial context on.
        api_key (str, optional): Your Azure API key. If None, will use AZURE_API_KEY from config.
        endpoint_url (str, optional): Azure endpoint. If None, will use endpoint from config.
        model_name (str): The deployed model name (default 'gpt-4o').
    Returns:
        str: The spatial context description generated by GPT-4o.
    """
    tp1 = time.time()
    if api_key is None:
        api_key = AZURE_API_KEY
    if endpoint_url is None:
        endpoint_url = endpoint
    if not api_key or not endpoint_url:
        raise ValueError("API key and endpoint must be provided or set in config.")

    # Prepare a textual summary of detections for GPT
    detection_summary = f"TARGET FOUND: {label}\n"
    if 'horizontal_position' in target_detection and 'vertical_position' in target_detection and 'depth_feet' in target_detection:
        detection_summary += f"Target location: {target_detection['horizontal_position']} side, {target_detection['vertical_position']}, approximately {target_detection['depth_feet']:.1f} feet away\n\n"
    else:
        detection_summary += f"Target location: {target_detection['bbox']}\n\n"
    detection_summary += "Other objects in scene:\n"

    for det in found_detections:
        if det != target_detection:
            # Show bbox for all, and spatial info if available
            line = f"- {det['class_name']} ({det['confidence']:.2f}), bbox: {det['bbox']}"
            if 'horizontal_position' in det and 'vertical_position' in det and 'depth_feet' in det:
                line += f", {det['horizontal_position']} side, {det['vertical_position']}, {det['depth_feet']:.1f} feet away"
            detection_summary += line + "\n"
    client = ChatCompletionsClient(
        endpoint=endpoint_url,
        credential=AzureKeyCredential(api_key),
    )
    tp2 = time.time()
    print(f"[Time] Azure client setup  and detection summary took {tp2 - tp1:.2f} seconds")
    # Encode frame to base64
    print("+"*100)
    print('calling gpt')
    print("+"*100)
    
    t0 = time.time()
    response = client.complete(
        messages=[
            SystemMessage(content="""You are an AI navigation assistant for visually impaired users.
    Provide clear, concise navigation instructions focusing on:
    1. Target object location and distance
    2. Obstacles or helpful landmarks for navigation
    3. Step-by-step guidance for reaching the target
    4. Safety considerations

    Use simple language and specific distances. Format like: 'The [object] is [position] at [distance]. To reach it, [navigation steps]. Watch out for [obstacles].'"""),
            UserMessage(content=[
                {"type": "text", "text": f"""Provide navigation guidance for a visually impaired person to locate this object: {detection_summary}"""},
                {
                    "type": "image_url",
                    "image_url": {"url": f"data:image/jpeg;base64,{frame}"}
                }
            ])
        ],
        max_tokens=300,
        temperature=0.7,
        top_p=0.9,
        model=model_name
    )
    t1 = time.time()
    print(f"[Time] GPT-4o response took {t1 - t0:.2f} seconds")
    return response.choices[0].message.content.strip()



